# Generated by Django 4.1.6 on 2023-02-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuIteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='menu')),
                ('desc', models.TextField()),
            ],
        ),
    ]
